### ISSUE TITLE
Request to Cease Blocking DaartAds' Main Domain (daartads.com)

### ISSUE THREAD

**Issue by aljvdi** [MasterKia/PersianBlocker#191]
Dear @MasterKia,
I am writing on behalf of DaartAds, an ad-exchange platform, about the ad-blocking activities directed towards our main domain, daartads.com. 

Whilst we appreciate your commitment to an ad-free online experience, we wish to draw your attention to the significant financial damages incurred by our operations due to blocking our primary domain.

DaartAds operates as an intermediary ad broker, facilitating the exchange of advertisements between customers seeking to display their ads and publishers interested in showcasing them on their platforms. We achieve this by serving advertisements through our API URL, `api.daartads.com`, rather than the entire website (daartads.com).

We want to let you know that we acknowledge your desire to avoid exposure to advertisements while browsing the internet; however, the complete blocking of our main domain has severe consequences for our business. 

As a result of the ad-blocking activities, our ability to generate revenue and sustain our operations is adversely affected, jeopardising the employment of our dedicated team members and hindering our ability to provide valuable services to our customers and publishers.

Given the circumstances, we kindly request that you reconsider blocking our main domain, daartads.com, while ensuring that your ad-blocking efforts are confined to specific ad-serving URLs, such as `api.daartads.com`, to maintain a fair balance between your preferences and sustainability.

We understand the importance of user experience and privacy concerns and endeavour to address these issues without compromising our financial viability. So, we are open to collaborating with you to explore potential solutions to help ease the experience while safeguarding our operations.

Cooperation and understanding between parties can lead to a harmonious online environment for all users, where advertisements are presented unobtrusively, and businesses can continue to thrive without undue hindrances.

Thank you for your time and attention to this matter. We are excited to hear from you soon.

Regards,
Alex Javadi
Technical Lead - Daart Digital Agency UK (Parent company of DaartADS)

86-90 Paul Street
London, United Kingdom, EC2A 4NE
it [at] daartads [dot] com

**Comment by DRSDavidSoft** [comment]
Dear Alex Javadi,

I am a part-time contributor to @MasterKia's blocking list, and I wanted to share my opinions on this matter with you.

Please let me state that I appreciate your understanding of our desire to avoid online advertisements and privacy concerns to the extent possible.

I think you have a lot of skills and expertise as a solutions engineer at Daart Digital Agency UK, and I also want to praise you for your willingness to collaborate and cooperate with MasterKia and me on this issue.  It's great that a company such as DaartAds is showing a lot of respect and professionalism in their communication, and the fact that you are open to finding a mutually beneficial solution.

Please note that I understand that **DaartAds** is trying to protect its business and revenue from the ad-blocking activities that may affect its main domain.  On the other hand, I also understand that MasterKia and other ad-blocker users have their reasons to avoid exposure to advertisements and protect their privacy and user experience.

In my opinion, the end-users who install and make use of such block lists, value their online experience and security while browsing the web, and generally don't have broad trust in any third-party ad providers that they encounter.

Please note that it is the policy of **PersianBlocker** and many other block lists to also block the root domains of companies dedicated to advertising platforms and solutions.  There is an important reason for doing so, as this allows many blocking software (that are able to interpret the root level domains as wildcards) to effectively block all the ad-serving subdomains under them as well.

This is intended and wanted behavior, since the list maintainers can account for all the different subdomains that may serve advertisements or track user behavior under that root domain, and reduce the overall number of host entries that are present in the list, which is important for performance and bandwidth-usage reasons.

One important example of such a domain is `doubleclick.net`, which is owned by Google advertising platforms.  There are many other similar domains present in both **PersianBlocker** and a similar block list that I maintain as well.  I'm afraid that we cannot discriminate between different ad-serving companies, however small or large.  For this reason, we need to continue blocking the main domain of DaartAds, `daartads.com`.

I understand your concerns about the potential financial damages caused by blocking your primary domain, but I also want to explain widespread issues with online advertisements overall, such as inconvenient banners, intrusive pop-ups, annoying "native" text ads, excessive bandwidth usage, or privacy violations.

Additionally, I want to explain that the end-users who are using this blocking list **want to avoid** advertisement platforms, solutions, and companies altogether, as they do not see any value or benefit in them.  I'd like to explain that if an end-user actually wants to visit such websites, the expected behavior is to disable the blocking software on that particular website. Here are some links to popular ad-blocking extensions that explain how to disable the extension on certain websites:

- uBlock Origin: https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site
- AdGuardHome: https://adguard.com/en/blog/how-to-unblock-website-adguard.html

I also want to let you know that the correct place to submit such a request is the "unbreak" lists.  These are lists that are designed to fix issues caused by blocking certain domains or URLs that may break some websites or functionalities. However, these lists are not meant to whitelist any ad platforms or companies, but only to unblock specific elements that are essential for the proper functioning of a website. For example, if blocking `daartads.com` prevents a user from accessing a website's login page or payment system, then an exception rule can be added to the unbreak list to allow those elements. However, this does not mean that `daartads.com` will be unblocked entirely, as the ad-serving URL api.daartads.com will still be blocked by default.

Please be aware that in our policy, we believe that advertisements are harmful and unnecessary for the online environment, and we support a free and open internet.  I think that any end-users that choose to use blocking lists such as this one share this belief, and would like to avoid exposure to advertisements and protect their privacy.

I acknowledge that there are many people who do not use block lists or blocking software altogether, and they may have different preferences and opinions on this subject.  

For example, **Linus Sebastian**, a popular tech YouTuber and influencer, has stated his perspective on ad blockers. Linus has stated in his videos that he considers ad blockers to be unethical and unfair, as they deprive content creators and platforms of their revenue and livelihood, as they allow users to enjoy free content without supporting the creators or the platforms that host them. He has also expressed his frustration and disappointment with users who use ad blockers on his videos, as they affect his income and his ability to produce quality content. Linus has said that he does not use ad blockers himself, and he encourages his viewers to disable them or whitelist his channel.

I respect Linus and his opinion, but I do not agree with him on this issue. I think that ad blockers are ethical and fair, as they allow users to protect their privacy and security, and to have control over their online experience. I also think that ad blockers are not the only or the main cause of the decline in revenue for content creators and platforms, as there are other factors such as market saturation, competition, algorithm changes, or policy violations. I also think that there are other ways to support content creators and platforms besides watching ads, such as donations, subscriptions, sponsorships, or merchandise purchases. I also think that content creators and platforms should respect their users' choices and preferences, and not force them to watch ads or **guilt-trip them for using ad blockers**.

Personally, I find DaartAds and your types of services intriguing.  Can you please explain what activities are your company involved with, and what kind of services you provide?  Can you please also provide some evidence or testimonials that can demonstrate DaartAds' quality and credibility, such as independent audits, reviews, ratings, or certifications?

We might be open to reconsidering blocking your main domain if you can prove that DaartAds is a reliable and ethical platform that does not compromise the end-user rights and interests, and does not facilitate any other subdomains besides `api.daartads.com` to serve ads, or other types of content that this list aims to block.

However, I also want to state the conditions and expectations for doing so, such as transparency, accountability, and user control. 

I also warn you that MasterKia reserves the right to reject and refuse any removals due to valid reasons, especially if:

- The evidence or testimonials are insufficient, outdated, biased, or falsified.
- The platform or company has a history or reputation of violating user privacy, security, or experience.
- The platform or company has a conflict of interest or affiliation with other ad providers or trackers.
- The platform or company does not comply with the relevant laws or regulations in the relevant jurisdictions.

I am interested in collaborating with you and your company in finding solutions that can respect end-user preferences and sustainability, but we also need more information about how DaartAds operates and what kind of advertisements it serves.  Can you please explain how DaartAds is different from other ad platforms, and what kind of benefits it can provide to users and publishers? I also ask you to explain what possible benefits there are to unblock your main domain when the actual service is blocked, by blocking your subdomains. Furthermore, I ask you to explain how blocking your main domain might cause harm to your financial gains.

Ultimately, I think this issue reflects the broader challenges and opportunities of the online environment, where advertisements play a vital role in supporting businesses and content creators, but also pose some risks and inconveniences for users. Finding a balance between these aspects is not easy, but it is possible with cooperation and understanding.

I think the best way to approach this issue is to have an open and respectful dialogue between both parties, where each can express their concerns and expectations, and try to find a common ground that can satisfy both sides. I think your message is a good start for initiating such a dialogue, as you show your willingness to collaborate and explore potential solutions. However, I also think that @MasterKia has the right to decide whether he wants to engage with this matter or not, and what kind of ad-blocking activities he wants to pursue.

I appreciate your constructive and healthy discussions with us on this matter, and I thank you for your time and attention. I look forward to hearing from you soon. 

Thank you for your patience and cooperation.

Sincerely,
DRSDavidSoft

**Comment by aljvdi** [comment]
Dear @DRSDavidSoft,

Thank you for your thoughtful and detailed message expressing your opinions. I appreciate your willingness to engage in an open and respectful dialogue about ad blocking, online advertisements, and user preferences.

Before addressing your questions about DaartAds and our services, I want to let you know your concerns about online advertisements. It is true that online ads can be intrusive and annoying and can compromise user privacy and experience. Many users use ad-blockers to protect themselves from these issues, and their preferences should be respected.

At DaartAds, we understand the importance of balancing user experience and supporting businesses and content creators. We aim to provide advertisers with a reliable and ethical platform while being mindful of user rights and interests. We prioritise transparency and user control in our practices.

Also, I want to assure you and @MasterKia that DaartAds takes user privacy seriously and complies with relevant data protection regulations, including the [General Data Protection Regulation (GDPR)](https://ico.org.uk/for-organisations/data-protection-and-the-eu/data-protection-and-the-eu-in-detail/the-uk-gdpr/).

To provide you with some information about DaartAds and our services:

DaartAds is an advertising platform that connects advertisers with publishers. We offer various advertising solutions, including display ads, native ads, video ads, and more. Our forum is designed to help advertisers effectively reach their target audience while ensuring publishers can monetise their content.

As for evidence of our quality and credibility, we have undergone independent audits and have received positive reviews and ratings from our clients and partners. We comply with relevant laws and regulations in the jurisdictions where we operate. We take user privacy seriously and do not engage in any practices that compromise user experience or security.

Users may experience issues such as displaying our platform's websites without CSS by blocking our primary domain. This can prevent us from effectively introducing ourselves to potential clients, including startups seeking to boost their revenue by placing ads and showcasing their services.

![image](https://github.com/MasterKia/PersianBlocker/assets/15309978/fd26d5b6-f238-4de6-9df0-49f71e5db7c7)

We acknowledge that users have the right to protect their privacy and not be tracked by any advertising system. We respect these preferences and are committed to ensuring our advertising practices align with user expectations and privacy concerns.

While we understand the reasons for ad blocking and its potential benefits for users, we also want to emphasise the positive contributions that ethical and non-intrusive advertising can make for businesses and content creators. When done responsibly, advertising can support various industries, drive innovation, and provide valuable information to users.

We aim to find a balance that respects user privacy while supporting businesses and publishers relying on advertising to sustain their operations. We are open to discussing possible solutions to address these concerns and enable a harmonious online environment for all stakeholders.

We appreciate your willingness to talk and look forward to further dialogue to find common ground that respects the interests and rights of all parties involved.

Even if @MasterKia chooses not to change our main domain to our subdomain, we respect his decision. We remain committed to ensuring user privacy and providing non-intrusive and ethical advertising solutions that align with the values and preferences of the online community. We value the trust and support of our users, and we will strive to be a responsible and respectful participant in the digital landscape.

I appreciate your understanding, and we look forward to continuing to serve our users in a way that respects their privacy and enhances the overall user experience.

Kind Regards,
Alex Javadi
Technical Lead - Daart Digital Agency UK (Parent company of DaartADS)

**Comment by aljvdi** [comment]
> There's no privacy policy to be found on the website daartads.com.
>
We regret to inform you that our privacy policy has yet to be published on our website; however, it will be included in our second version. We want to stress that DaartAds takes user privacy seriously, and to demonstrate our commitment; we have signed a comprehensive GDPR policy agreement with the United Kingdom government. Unfortunately, because of confidential information about our company within this agreement, we cannot publish it on our website right now.

> Please provide a link to the privacy laws of Iran, which is where you're operating. As far as I know, there's none.
>

Whilst Iran does not currently have specific privacy policy agreements mandated by law, we want to assure our users that we still prioritise their privacy and security. Even though there might not be specific regulations, we adhere to ethical principles and strive to protect user data as per international standards. We comply with relevant laws and regulations in all our jurisdictions, ensuring that user data is treated with utmost care and confidentiality.

We hereby inform you that, due to the current workload demands and priorities, we have officially closed the ongoing discussion thread related to the matter under consideration.

**Comment by DRSDavidSoft** [comment]
@aljvdi Thank you for your thorough response. I'm still interested and committed to preventing the end-user from ever seeing the screenshot you shared with us above. 

Please, whenever you had sufficient time, let's continue discussing this over at:
https://github.com/AdguardTeam/AdguardFilters/issues/157806#issuecomment-1658975165

I particularly don't understand the circumstances that would lead to the extension displaying a "broken" version of DaartAds' homepage. This is certainly not acceptable. As stated over the link above, the user should either see the "blocked" screen -- which I shared in the link above --, or the "correct" version of the homepage, which includes the stylesheets and javascript files. In no case the user should ever see the broken page, thus your initial concerns are still valid.

@MasterKia Thank you for your participation. I hope @aljvdi and I would reach a constructive conclusion over the initial issue linked above, whenever he has time.
